spring.application.name=MailSense-AI
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
gemini.api.key=${GEMINI_KEY}

gemini.embed.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent
style.store.path=./style-store.json
mailsense.sender-name=Ayush
server.error.include-message=always
gemini.fallback.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-lite-latest:generateContent